language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed babuuh/udagram-api-feed:v2
  - docker tag udagram-api-user babuuh/udagram-api-user:v2
  - docker tag udagram-frontend babuuh/udagram-frontend:v2
  - docker tag udagram-reverseproxy babuuh/udagram-reverseproxy:v4

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push babuuh/udagram-api-feed:v2
- docker push babuuh/udagram-api-user:v2
- docker push babuuh/udagram-frontend:v2
- docker push babuuh/udagram-reverseproxy:v4