apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-user
  name: udagram-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
        service: udagram-api-user
    spec:
      containers:
      - image: babuuh/udagram-api-user
        name: udagram-api-user
        imagePullPolicy: Always          
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: udagramdb
          - name: POSTGRES_HOST
            value: udagram-dev-db.ctarpplxbzgk.us-east-1.rds.amazonaws.com
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: JWT_SECRET
        ports:
        - containerPort: 8080
      restartPolicy: Always