apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
        service: udagram-api-feed
    spec:
      containers:
      - image: babuuh/udagram-api-feed
        name: udagram-api-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"          
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: POSTGRES_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: JWT_SECRET
          - name: POSTGRES_DB
            value: udagramdb
          - name: POSTGRES_HOST
            value: udagramdb.ck6ephfnph3g.us-east-1.rds.amazonaws.com
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_PROFILE
            value: default
          - name: AWS_BUCKET
            value: udagramkihara-s3
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret